### ISSUE TITLE
Add GitHub sponsors

### ISSUE THREAD

**Issue by VernonGrant** [fritzgrabo/project-tab-groups#4]
Hi, If you don't mind, please add GitHub sponsor button to this project. I would like to support it with a couple dollars a month, if you don't mind.

**Comment by fritzgrabo** [comment]
@VernonGrant, it made my day to hear that you'd be willing to sponsor this project as (I assume) a token of appreciation, wow.

To be honest, knowing that there are folks out there who use my humble Emacs packages and like them is more than enough for me in terms of appreciation.

If you _do_ have a couple of bucks a month to spare, may I suggest sponsoring some of the tireless contributors to Emacs / Emacs packages who rely on that form of income to make a living. Jonas Bernoulli comes to mind, but I see he's already on your list. Then again, topping up your sponsoring for him by a few bucks a month surely won't hurt him 😅 

Thanks so much for reaching out, you've literally put a smile on my face by doing so.

**Comment by VernonGrant** [comment]
@fritzgrabo It's all good! I use this package daily, and its been a great addition to my workflow. Especially because I have so many different projects to work on. If you do decide to have your own sponsorship button in the future, let me know. Have a great day and thanks once again for contributing towards Emacs. 🙏🏻
