### ISSUE TITLE
Question regarding show/hide tabs

### ISSUE THREAD

**Issue by LionyxML** [fritzgrabo/project-tab-groups#8]
Hello there!

Thanks for this awesome package!

Quick question, I don't know if you can help me with.

I have several Projects opened, and I have an advice function that numerates all my tabs. The intention here is to make something similar to tmux.

I have tabs as 'tmux panes' and i use windows (as in C-x 5 2) as "workspaces" for each project.

Problem is on Emacs GUI those windows are separated windows and not something like TUI Emacs, thus, I rely on the window manager.

So with you package I managed to do something like:
- Groups are the "workspace"
- Tabs are my tabs

NICE!

Only problem, this line is now a mess:

<img width="761" alt="image" src="https://github.com/user-attachments/assets/5e33b304-a621-4948-941e-3d3fc1c224a8">

Is there any thing we can do about it?

I mean, is it possible to "hide" groups I am not "inside" and keep only the current (related to the opened tab) project tabs appearing?

**Comment by fritzgrabo** [comment]
Hey @LionyxML,

thanks for the kind words, I'm happy to hear you find this package useful! 🙌 

Regarding your question, if I understood you correctly, you want to hide all inactive tab-groups (including their tabs) in the tab-bar altogether? So in your screenshot above, the tab-bar would show just `auto-dark-emacs >>4<<` and nothing else?

If I got that right, then best check out the `tab-bar-format-tabs-groups` function ([link](https://github.com/emacs-mirror/emacs/blob/master/lisp/tab-bar.el#L1088)) that Emacs uses to build the list of grouped tabs for the tab-bar and the menu. You'll see that for each individual tab group, it calls `tab-bar--format-tab-group (tab i &optional current-p)` ([link](https://github.com/emacs-mirror/emacs/blob/master/lisp/tab-bar.el#L1052)), where `current-p` is true only _if this is the currently active tab group_.

I haven't tried it, but you might get away with advising `tab-bar--format-tab-group` to just return nothing if `current-p` is not true.

Let me know if I understood your question correctly, and if any of ^^ helps at all. Good luck!

**Comment by fritzgrabo** [comment]
PS: Slightly related, about the advice function you mentioned you use to numerate all tabs -- check out the `tab-bar-tab-hints` customization that Emacs provides. I think you might find it does the same thing? From its doc-string:

> Show absolute numbers on tabs in the tab bar before the tab name. This helps to select the tab by its number using ‘tab-bar-select-tab’ and ‘tab-bar-select-tab-modifiers’.

**Comment by LionyxML** [comment]
Thanks @fritzgrabo , That was exactly what I meant, I wanted only the tabs grouped by this project to appear. 

This would give me a similar workflow to the one I use with tmux (one project per session, multiple windows per project, would become one project by project-tab-group, several tabs for project).

(Just remembering we're talking about tab-bar not tab-line tabs, if anyone is reading this).

I haven't got the time to test your idea yet :/ but it seems promising.

Also I had no idea `tab-bar-tab-hints` existed, lol. My idea is changing the tab name with >>num<<, so it wont change if I change the tab content and it is not that small of a tab.

What I am doing is:
```elisp
(use-package tab-bar
  :ensure nil
  :defer t
  :custom
  (tab-bar-close-button-show nil)
  (tab-bar-new-button-show nil)
  :init
  ;; This aims to substitute tmux (or gnu/screen) with Emacs
  ;; Tabs are our tmux windows (new one with C-x t 2)
  ;; Windows are emacs windows (new one with C-x 5 2)

  (setq tab-bar-position t)

  (setq tab-bar-auto-width t)
  (setq tab-bar-auto-width-min '(10 4))
  (setq tab-bar-auto-width-max '(40 5))


  (defun lemacs/renumber-tabs (&optional include-file-name)
    "Renumber all tabs according to their position.
If INCLUDE-FILE-NAME is non-nil, include the file name in the tab name."
    (interactive "P")
    (let ((tabs (tab-bar-tabs)))
      (dotimes (i (length tabs))
        (let* ((tab (nth i tabs))
                (old-name (alist-get 'name tab))
                (file-name (if include-file-name
                             (replace-regexp-in-string "^\\([0-9]+) \\)" "" old-name)
                             ""))
                (new-name (format " »%d« %s" (1+ i) file-name)))
          (tab-bar-select-tab (1+ i)) ; Select the tab by its 1-based index
          (tab-bar-rename-tab new-name)))))


  ;; Whenever we modify tabs, we want it renumbered
  (advice-add 'tab-close :after #'lemacs/renumber-tabs)
  (advice-add 'tab-close-other :after #'lemacs/renumber-tabs)
  (advice-add 'tab-new :after #'lemacs/renumber-tabs)

  (advice-add 'tab-new :after #'lemacs/renumber-tabs)

  (add-hook 'tab-bar-groups-tab-post-change-group-functions #'tab-bar-groups-regroup-tabs)
  (add-hook 'tab-bar-groups-tab-post-change-group-functions #'lemacs/renumber-tabs)

  (defun lemacs/switch-tab-or-tab-bar ()
    "Switch between 2 tabs or choose if > 2 tabs are present."
    (interactive)
    (if (= (length (tab-bar-tabs)) 2)
      (tab-next)
      (call-interactively 'tab-bar-switch-to-tab)
      ))

  (global-set-key (kbd "M-r") 'lemacs/switch-tab-or-tab-bar))
```

**Comment by fritzgrabo** [comment]
@LionyxML awesome, I'm glad to hear I got your question correctly, and that the ideas in my answer sound promising to you. Also, thanks for sharing your solution for renumbering the tabs "tmux-style"; this might come in handy for other people coming to this thread with a similar issue 👍
